# Generated by Django 5.1.5 on 2025-01-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
