# Generated by Django 5.1.5 on 2025-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0002_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
