# Generated by Django 5.1.5 on 2025-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0004_article_author_article_voter_comment_voter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='voter',
        ),
    ]
